import json
import os
import httpx
import asyncio
import time
from openai import AsyncOpenAI

# ==========================================
# 1. 配置与初始化
# ==========================================
client = AsyncOpenAI(
    base_url="https://api.deepseek.com",
    api_key=os.getenv("OPENROUTER_API_KEY"),
    http_client=httpx.AsyncClient(
        timeout=300
    )
)


class Config:
    LMM_MODEL = "deepseek-reasoner"
    MAX_CONCURRENT_REQUESTS = 10


# ==========================================
# 2. 辅助函数
# ==========================================
def load_text_file(file_path: str) -> str:
    if not os.path.exists(file_path):
        return ""
    with open(file_path, 'r', encoding='utf-8') as f:
        return f.read()


def load_json(file_path: str) -> dict:
    """通用的 JSON 读取函数，用于读取 GT 或已有的断点输出文件"""
    if not os.path.exists(file_path):
        return {}
    with open(file_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def load_model_data(file_path: str) -> dict:
    if not os.path.exists(file_path):
        return {}
    data_dict = {}
    with open(file_path, 'r', encoding='utf-8') as f:
        if file_path.endswith('.jsonl'):
            for line in f:
                line = line.strip()
                if not line: continue
                try:
                    item = json.loads(line)
                    task_id = item.get("task_id")
                    if task_id:
                        data_dict[str(task_id)] = item.get("model_response", {})
                except Exception:
                    pass
        else:
            raw_data = json.load(f)
            for k, v in raw_data.items():
                task_id = os.path.splitext(k)[0]
                data_dict[str(task_id)] = v
    return data_dict


def save_json(data: dict, file_path: str):
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, 'w', encoding='utf-8') as f:
        # 【重点】加入了 sort_keys=True，保证乱序并发完成后，落盘依然是按 task_id 排序的
        json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)


def extract_json_from_response(text: str) -> dict:
    try:
        text = text.strip()
        if text.startswith("```json"):
            text = text.split("```json")[1].split("```")[0].strip()
        elif text.startswith("```"):
            text = text.split("```")[1].split("```")[0].strip()
        return json.loads(text)
    except Exception:
        return {}


def format_time(seconds: float) -> str:
    m, s = divmod(int(seconds), 60)
    h, m = divmod(m, 60)
    if h > 0:
        return f"{h:02d}时{m:02d}分{s:02d}秒"
    return f"{m:02d}分{s:02d}秒"


# ==========================================
# 3. 异步 LMM 评委核心调用逻辑
# ==========================================
async def run_lmm_judge_async(gt_json: dict, step_3_text: str, step_4_text: str, step_5_text: str, land_use_rules: str,
                              semaphore: asyncio.Semaphore) -> dict:
    prompt = f"""
[System]
You are a Spatial-Temporal Logic and Reasoning AI Judge. Your task is to evaluate the complex reasoning chain, spatial logical relations, and future state inferences generated by an AI analyzing remote sensing land-use changes.
You MUST strictly base your evaluation on the provided [Land-Use Taxonomy Rules].

[Task]
Evaluate the Model's Output for `step_3`, `step_4`, and `step_5` based on logical rigor, spatial understanding, and causal reasoning.

[Evaluation Criteria]
1. Step 3 (Relational Model): Evaluate spatial logic (9-grid absolute, relative positioning) and dense relationship completion (spatial, interactive, functional). Is the spatial reasoning physically possible and logically sound?
2. Step 4 (CoT Reasoning Quality): Does the model form a rigorous Chain-of-Thought? 
   - Positive Chain (Identify True Changes): Does it successfully identify truly changed instances while astutely identifying and filtering out "pseudo-changes" (e.g., illumination, phenology, shadows) with strong logical justifications?
   - Negative Chain (Filter Intra-class Changes): Among the identified true changes, does it accurately reference the [Land-Use Taxonomy Rules] to filter out invalid intra-class changes (A to B, but still belonging to the same Level 2 category)? Does it correctly confirm that the change is a valid inter-class change (between different Level 2 categories) required by our standard?
3. Step 5 (Future Inference): Is the prediction of future states grounded in the current analysis and real-world physical/functional concepts?

[Input Context]
- Land-Use Taxonomy Rules: 
\"\"\"
{land_use_rules}
\"\"\"
- GT Semantic Context: {json.dumps(gt_json, ensure_ascii=False)}

[Model's Predictions]
- Model Step 3 (Relational Model): {step_3_text}
- Model Step 4 (Reasoning CoT): {step_4_text}
- Model Step 5 (Future Inference): {step_5_text}

[Output Format]
Provide your evaluation in strict JSON format exactly like this:
{{
  "judge_2_eval": {{
    "step_3_score": [Score 0-10],
    "step_3_reasoning": "[1-2 sentences evaluating spatial and relational logic]",
    "step_4_logic_score": [Score 0-10],
    "step_4_reasoning": "[1-2 sentences evaluating CoT quality, especially focusing on how well it executed the positive chain (true vs pseudo changes) and the negative chain (inter-class vs intra-class changes)]",
    "step_5_score": [Score 0-10],
    "step_5_reasoning": "[1-2 sentences evaluating plausibility of future inference]"
  }}
}}
"""
    async with semaphore:
        try:
            response = await client.chat.completions.create(
                model=Config.LMM_MODEL,
                messages=[{"role": "user", "content": prompt}],
                stream=False
            )
            result_text = response.choices[0].message.content
            return extract_json_from_response(result_text)
        except Exception as e:
            return {"error": str(e)}


async def process_single_task(model_name, clean_task_id, current_gt_semantics, step_3_text, step_4_text, step_5_text,
                              land_use_rules_text, semaphore, lmm_evaluations, counter_info, output_save_path):
    eval_result = await run_lmm_judge_async(
        gt_json=current_gt_semantics,
        step_3_text=step_3_text,
        step_4_text=step_4_text,
        step_5_text=step_5_text,
        land_use_rules=land_use_rules_text,
        semaphore=semaphore
    )

    lmm_evaluations[model_name][clean_task_id] = eval_result

    # 时间与进度计算逻辑
    counter_info['processed'] += 1
    processed = counter_info['processed']
    total = counter_info['total']
    start_time = counter_info['start_time']

    elapsed = time.time() - start_time
    avg_time_per_task = elapsed / processed
    remaining = avg_time_per_task * (total - processed)
    est_total = elapsed + remaining

    s3 = eval_result.get('judge_2_eval', {}).get('step_3_score', 'Err')
    s4 = eval_result.get('judge_2_eval', {}).get('step_4_logic_score', 'Err')
    s5 = eval_result.get('judge_2_eval', {}).get('step_5_score', 'Err')

    print(
        f"\n[+] 进度: [{processed}/{total}] | 模型: {model_name} | 任务: {clean_task_id} 评估完成 -> Step3:{s3}, Step4:{s4}, Step5:{s5}")
    print(
        f"    ⏳ 耗时统计: [本次运行已耗时: {format_time(elapsed)}] | [预计剩余: {format_time(remaining)}] | [预计本次总需: {format_time(est_total)}]")

    if processed % 20 == 0:
        save_json(lmm_evaluations, output_save_path)
        print(f"    💾 [系统提示] 已自动保存中间结果...")


# ==========================================
# 4. 异步主执行流程
# ==========================================
async def main_async():
    # ------------------ 用户配置区 ------------------
    LAND_USE_MD_PATH = r"land-use.md"
    GT_JSON_PATH = r"change_regions_merged_test.json"

    MODEL_JSON_PATHS = [
        "judge/change-answer/gemini_answer_change.jsonl",
        "judge/change-answer/gpt41_answer_change.jsonl",
        "judge/change-answer/llava_answer_change.jsonl",
        "judge/change-answer/qvq_answer_change.jsonl",
        "judge/change-answer/qwen_answer_change.jsonl"
    ]

    OUTPUT_SAVE_PATH = "judge/judge-output/change_judge_2_lmm_batch_results-async-deepseek.json"
    # ------------------------------------------------

    print("[*] 开始执行 LMM 纯文本逻辑评委 (Stage 2) 批量打分阶段 (异步断点续传模式)...")

    land_use_rules_text = load_text_file(LAND_USE_MD_PATH)
    gt_data_all = load_json(GT_JSON_PATH)

    models_data = {}
    for path in MODEL_JSON_PATHS:
        model_name = os.path.splitext(os.path.basename(path))[0]
        models_data[model_name] = load_model_data(path)
        print(f"[+] 成功加载模型预测数据: {model_name} (共 {len(models_data[model_name])} 条)")

    # ================= 【断点续传核心逻辑开始】 =================
    if os.path.exists(OUTPUT_SAVE_PATH):
        print(f"[*] 发现已存在的输出文件 {OUTPUT_SAVE_PATH}，正在读取断点数据...")
        lmm_evaluations = load_json(OUTPUT_SAVE_PATH)
        # 确保所有待测模型的 Key 都存在于字典中
        for name in models_data.keys():
            if name not in lmm_evaluations:
                lmm_evaluations[name] = {}
    else:
        print(f"[*] 未发现历史输出文件，将从头开始建立全新评估。")
        lmm_evaluations = {name: {} for name in models_data.keys()}
    # ================= 【断点续传核心逻辑结束】 =================

    all_task_ids = list(gt_data_all.keys())
    task_params_list = []
    already_completed_count = 0

    for task_id in all_task_ids:
        clean_task_id = str(task_id).split('.')[0][:6]
        current_gt_data = gt_data_all.get(task_id, {})
        current_gt_semantics = current_gt_data.get("semantics", {})

        for model_name, model_output_all in models_data.items():

            # --- 【检查该任务是否已经完成】 ---
            existing_result = lmm_evaluations.get(model_name, {}).get(clean_task_id)
            # 只有当结果存在，且里面没有包含 "error" 字段时，才认为是有效完成的断点
            if existing_result and "error" not in existing_result:
                already_completed_count += 1
                continue
            # -----------------------------------

            current_model_data = model_output_all.get(clean_task_id)
            if not current_model_data:
                continue

            thought_process = current_model_data.get("thought_process", {})
            step_3_text = thought_process.get("step_3_relational_model", "")
            step_4_text = thought_process.get("step_4_reasoning", "")
            step_5_text = thought_process.get("step_5_future_inference", "")

            if not step_3_text and not step_4_text and not step_5_text:
                continue

            task_params_list.append({
                "model_name": model_name,
                "clean_task_id": clean_task_id,
                "current_gt_semantics": current_gt_semantics,
                "step_3_text": step_3_text,
                "step_4_text": step_4_text,
                "step_5_text": step_5_text
            })

    total_tasks = len(task_params_list)
    print(f"[*] 任务检查完毕！已跳过 {already_completed_count} 个已完成的任务。")
    print(f"[*] 🚀 本次实际需要投递 {total_tasks} 个 API 请求...")

    if total_tasks == 0:
        print("[*] 🎉 所有任务均已评估完成，无需执行任何请求！")
        return

    semaphore = asyncio.Semaphore(Config.MAX_CONCURRENT_REQUESTS)
    counter_info = {
        'processed': 0,
        'total': total_tasks,
        'start_time': time.time()
    }

    async_tasks = []
    for params in task_params_list:
        task = asyncio.create_task(process_single_task(
            model_name=params['model_name'],
            clean_task_id=params['clean_task_id'],
            current_gt_semantics=params['current_gt_semantics'],
            step_3_text=params['step_3_text'],
            step_4_text=params['step_4_text'],
            step_5_text=params['step_5_text'],
            land_use_rules_text=land_use_rules_text,
            semaphore=semaphore,
            lmm_evaluations=lmm_evaluations,
            counter_info=counter_info,
            output_save_path=OUTPUT_SAVE_PATH
        ))
        async_tasks.append(task)

    await asyncio.gather(*async_tasks)

    total_time_cost = time.time() - counter_info['start_time']
    save_json(lmm_evaluations, OUTPUT_SAVE_PATH)
    print(f"\n[*] 🎉 阶段二 (LMM 纯文本异步批量评估) 脚本执行完毕！")
    print(f"[*] 🏆 本次运行成功补充了 {total_tasks} 个评估，实际总耗时: {format_time(total_time_cost)}")


if __name__ == "__main__":
    asyncio.run(main_async())